server:
  port: 5001
  servlet:
    context-path: /datadic
# mybatis 配置
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.bfd.largescreem.bean
  configLocation: classpath:config/mybatis.xml

jedis:
  pool:
    configstr: master:xxx.xx.xx.xx:6379
    password: xxx
    timeout: 3000
    config:
      maxTotal: 300
      maxIdle: 200
      maxWaitMillis: 1000
#redission配置
#redisson版本是3.5，集群的ip前面要加上“redis://”，不然会报错，3.2版本可不加
redisson:
  master-name: stgmaster
  password: huyihan
  master-address: redis://xxx.xx.xxx.xx:6379
  slave-addresses:
spring:
  cloud:
    nacos:
      discovery:
        server-addr: xx.xx.xx.xx:5055
  application:
    name: service-provider

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/manager?autoReconnect=true&roundRobinLoadBalance=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: root
    #连接池的配置信息
    minIdle: 5
    maxActive: 100
    initialSize: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select * from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
    removeAbandoned: true
    filters: stat # ,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
#management:
#  endpoints:
#    web:
#      exposure.exclude=*
